feat: get token from tmp file
suborbital/subo pull request #111
Opened 2021-10-26 02:43 UTC by zhangwinning

fix https://github.com/suborbital/subo/issues/109

cc @jagger27 @cohix

2021-11-04 22:58 UTC, cohix approved these changes
@zhangwinning my apologies for letting this sit, I have been travelling.

This looks great to me. @jagger27 can you please test this locally and then merge if it all works as expected?

2021-11-11 13:01 UTC, zhangwinning commented
please cc @jagger27

2021-11-11 18:00 UTC, jagger27 requested changes
Sorry for the long delay @zhangwinning, and thanks again for this contribution.

I'm wonder whether we should also remove the temporary file once it has been successfully copied to SCC.env.

Please rebase on `main` as well!

2021-11-12 16:16 UTC, jagger27 approved these changes

2021-11-12 17:25 UTC, merged