tweak(subo): Rename scc -> scn in subo everywhere
suborbital/subo pull request #334
Opened 2022-07-26 16:09 UTC by javorszky

Closes #332 

Replaces #333 

- also fixed a variable / package name collision
- moved some details to consts, and updated usages accordingly

2022-07-28 17:19 UTC, ospencer reviewed
It looks like there are a lot of linting-related changes that aren't related to the SCC -> SCN swap. Should we land those separately?

2022-07-28 17:47 UTC, arbourd reviewed
Could we also normalize to `controlplane` over `control-plane`? This was always intended for the Docker images.

2022-07-28 17:47 UTC, arbourd commented on templates/scc-docker/docker-compose.yml.tmpl
> +    image: suborbital/scn-control-plane:{{ .SCNVersion }}
```suggestion
  scn-controlplane:
    image: suborbital/scn-controlplane:{{ .SCNVersion }}
```

2022-07-28 17:47 UTC, arbourd commented on templates/scc-docker/docker-compose.yml.tmpl
> +      - scn-control-plane
```suggestion
      - scn-controlplane
```

2022-07-28 17:47 UTC, arbourd commented on templates/scc-docker/docker-compose.yml.tmpl
> +      ATMO_CONTROL_PLANE: "scn-control-plane:8081"
```suggestion
      ATMO_CONTROL_PLANE: "scn-controlplane:8081"
```

2022-07-28 17:47 UTC, arbourd commented on templates/scc-k8s/.suborbital/scc-controlplane-deployment.yaml.tmpl
> +          image: suborbital/scn-control-plane:{{ .SCNVersion }}
```suggestion
          image: suborbital/scn-controlplane:{{ .SCNVersion }}
```

2022-08-01 09:25 UTC, javorszky commented
> It looks like there are a lot of linting-related changes that aren't related to the SCC -> SCN swap. Should we land those separately?

@ospencer on one hand I understand the need for it, on the other, the linting was broken in the previous version as it used the linting config from a previous version of gci.

I figured if I have to change _some_ of the linting anyways, I might as well standardise the lints between subo and scn (gci and revive to unearth the import shadows).

To me it's a case of the boyscout rule (leave code looking better than you found it) in this case, and because it's somewhat related, I think it's fine to leave them in for now. Generally I try to separate out things into different PRs.

2022-08-01 14:59 UTC, ospencer approved these changes

2022-08-02 20:12 UTC, arbourd requested changes
Requires an SCC release

2022-11-22 02:26 UTC, arbourd commented
Closing this as it has been done in `suborbital/templates`. Thanks @javorszky!

2022-11-22 02:26 UTC, closed without merging